name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: cheatsheet.tex
